image: oven/bun:1.3-debian

variables:
  BUN_INSTALL_CACHE_DIR: "$CI_PROJECT_DIR/.bun-cache"

.releases:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|beta|alpha)$/ && $CI_PIPELINE_SOURCE != 'schedule' && $CI_COMMIT_MESSAGE =~ /^(feat|fix).*/

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/ || $CI_COMMIT_TAG
      when: never
    - when: always

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .bun-cache

before_script:
  - apt-get update -qq
  - apt-get install -y -qq curl git ack python3 build-essential libxi-dev libgl1-mesa-dev libglew-dev pkg-config
  - bun ci

stages:
  - test
  - build
  - release

variables:
  PACKAGE_REGISTRY_URL: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/module

biome:
  stage: test
  script:
    - bun biome ci --reporter=gitlab --reporter-file=code-quality.json
  artifacts:
    when: always
    reports:
      codequality: code-quality.json
  rules:
    - changes:
        paths:
        - src/**/*.js
        - scripts/**/*.js
        - module.json
        - lang/**/*.json
        - models/**/*.json

build:
  stage: build
  script:
    - export VERSION=$(bun semantic-release --dry-run | ack -io '(?<=The next release version is )(.*)(?=$)') && echo VERSION=$VERSION >> build.env
    - export MANIFEST=$CI_PROJECT_URL/-/releases/permalink/latest/downloads/module.json && echo MANIFEST=$MANIFEST >> build.env
    - export DOWNLOAD=$CI_PROJECT_URL/-/releases/v$VERSION/downloads/module.zip && echo DOWNLOAD=$DOWNLOAD >> build.env
    - bun run build
    - bun run package
  artifacts:
    name: module
    when: on_success
    reports:
      dotenv: build.env
    paths:
      - module.zip
      - module.json
  extends: .releases

publish:
  stage: release
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file module.zip $PACKAGE_REGISTRY_URL/$VERSION/module.zip'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file module.json $PACKAGE_REGISTRY_URL/$VERSION/module.json'
  dependencies:
    - build
  extends: .releases

release:
  stage: release
  script:
    - bun semantic-release
  dependencies:
    - build
  extends: .releases
